trigger:
- main

resources:
- repo: self

variables:
  tag: '60' #'$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    # - task: Docker@2
    #   displayName: Build an image
    #   inputs:
    #     command: build
    #     dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    #     tags: |
    #       $(tag)

    # - task: CmdLine@2
    #   displayName: 'Install emulator'
    #   inputs:
    #     script: 'sudo apt-get install -y qemu qemu-user-static'
    # - task: Docker@2
    #   displayName: Build image
    #   inputs:
    #     containerRegistry: 'docker-hub'
    #     repository: 'jarrettd5309/currency-exchange-devops'
    #     command: 'build'
    #     Dockerfile: '**/Dockerfile'
    #     tags: '$(tag)'
    #     arguments: '--platform linux/arm64'
    # - task: Docker@2
    #   displayName: Push image
    #   inputs:
    #     containerRegistry: 'docker-hub'
    #     repository: 'jarrettd5309/currency-exchange-devops'
    #     command: 'push'
    #     tags: '$(tag)'

    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/*.yaml'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'manifests'
        publishLocation: 'Container'
- stage: Deploy
  displayName: Deploy image
  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'manifests'
        itemPattern: '**/*.yaml'
        targetPath: '$(System.ArtifactsDirectory)'
    - task: KubernetesManifest@1
      inputs:
        action: 'deploy'
        connectionType: 'kubernetesServiceConnection'
        kubernetesServiceConnection: 'aws-kub-cluster-sevice-connection'
        namespace: 'default'
        manifests: '$(System.ArtifactsDirectory)/configuration/kubernetes/deployment.yaml'
        containers: 'jarrettd5309/currency-exchange-devops:$(tag)'